// Generated by to_mdx.py — chapter order for the sidebar and prev/next.
// `n: null` marks a hand-written page that sits outside the numbering, so
// adding one never desyncs the chapter numbers used in headings and §refs.
export const BASE = "/articles/personal-finance-india"

export const chapters = [
  { n: 0, href: "/articles/personal-finance-india", label: "Start here", group: "Overview" },
  { n: 1, href: "/articles/personal-finance-india/first-principles", label: "First principles", group: "The ground rules" },
  { n: 2, href: "/articles/personal-finance-india/offer-letter", label: "Decoding an offer letter", group: "Getting paid" },
  { n: 3, href: "/articles/personal-finance-india/equity-compensation", label: "Equity compensation", group: "Getting paid" },
  { n: 4, href: "/articles/personal-finance-india/tax-regimes", label: "Old regime vs new regime", group: "Tax" },
  { n: 5, href: "/articles/personal-finance-india/salary-structuring", label: "Allowances & perquisites", group: "Tax" },
  { n: 6, href: "/articles/personal-finance-india/worked-example", label: "Worked example: \u20b918L CTC", group: "Tax" },
  { n: null, href: "/articles/personal-finance-india/calculator", label: "Salary calculators", group: "Tax" },
  { n: 7, href: "/articles/personal-finance-india/epf-eps-form-11", label: "EPF, EPS, Form 11, gratuity", group: "Mandatory savings" },
  { n: 8, href: "/articles/personal-finance-india/nps", label: "NPS", group: "Mandatory savings" },
  { n: 9, href: "/articles/personal-finance-india/insurance", label: "Insurance", group: "Protection" },
  { n: 10, href: "/articles/personal-finance-india/credit-cards-cibil", label: "Credit cards & CIBIL", group: "Debt & credit" },
  { n: 11, href: "/articles/personal-finance-india/loans-and-debt", label: "Loans & getting out of debt", group: "Debt & credit" },
  { n: 12, href: "/articles/personal-finance-india/investing", label: "Investing", group: "Investing" },
  { n: 13, href: "/articles/personal-finance-india/fixed-income-and-gold", label: "Fixed income, gold & crypto", group: "Investing" },
  { n: 14, href: "/articles/personal-finance-india/goals-and-planning", label: "Goals & planning", group: "Goals & life" },
  { n: 15, href: "/articles/personal-finance-india/real-estate", label: "Real estate", group: "Goals & life" },
  { n: 16, href: "/articles/personal-finance-india/family-and-succession", label: "Family & succession", group: "Goals & life" },
  { n: 17, href: "/articles/personal-finance-india/numbers", label: "The numbers page", group: "Reference" },
  { n: 18, href: "/articles/personal-finance-india/forms-and-links", label: "Forms, schemes & links", group: "Reference" },
]
